FROM node:10-alpine
RUN set -eux \
    && mkdir /app \
    && chown node:node /app
WORKDIR /app
RUN set -eux \
    && USER=node \
    && GROUP=node \
    && apk add --virtual virtual curl \
    && curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.4/fixuid-0.4-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - \
    && apk del virtual \
    && chown root:root /usr/local/bin/fixuid \
    && chmod 4755 /usr/local/bin/fixuid \
    && mkdir -p /etc/fixuid \
    && printf "user: $USER\ngroup: $GROUP\n" > /etc/fixuid/config.yml
ENV PORT=3000
ENV VUE_APP_API_URL=http://localhost:3000
EXPOSE $PORT
