version: '3'

services:
  backend:
    image: 'golang:1.17'
    working_dir: /go/src/app
    ports:
      - '6060:6060/tcp'
    volumes:
      - ./backend:/go/src/app:rw
    command: tail -f /dev/null

  envoy:
    build:
      context: envoy
    ports:
      - '3000:3000/tcp'
      - '9901:9901/tcp'
    depends_on:
      - backend

  frontend:
    image: 'node:lts-alpine3.15'
    working_dir: /app
    ports:
      - '80:3000/tcp'
    depends_on:
      - envoy
    volumes:
      - ./frontend:/app:rw
    command: tail -f /dev/null
