version: '3'

services:
  backend:
    build:
      context: backend
    ports:
      - '6001:6001/tcp'
      - '6060:6060/tcp'
    env_file:
      - backend/.env

  frontend:
    build:
      context: frontend
    ports:
      - '80:80/tcp'
    env_file:
      - frontend/.env
