version: '3'

services:
  backend:
    image: 'golang:1.19'
    working_dir: /go/src/app
    ports:
      - '6001:6001/tcp'
      - '6060:6060/tcp'
    volumes:
      - ./backend:/go/src/app:rw
    command: tail -f /dev/null

  frontend:
    image: 'node:lts-alpine3.15'
    working_dir: /app
    ports:
      - '80:3000/tcp'
    volumes:
      - ./frontend:/app:rw
    command: tail -f /dev/null
