version: '3'

services:
  backend:
    build:
      context: backend
      args:
        NAME: backend
        VERSION: 1.0.0-dev
    ports:
      - '8000:8000/tcp'
      - '8001:8001/tcp'
      - '8002:8002/tcp'
    env_file:
      - backend/.env

  frontend:
    build:
      context: frontend
    ports:
      - '80:80/tcp'
    env_file:
      - frontend/.env
