version: '3'

services:
  backend:
    image: 'golang:1.21-alpine3.18'
    working_dir: /go/src/app
    ports:
      - '8000:8000/tcp'
      - '8001:8001/tcp'
      - '8002:8002/tcp'
    volumes:
      - ./backend:/go/src/app:rw
    command: tail -f /dev/null

  frontend:
    image: 'node:21.0.0-alpine3.18'
    working_dir: /app
    ports:
      - '80:3000/tcp'
    volumes:
      - ./frontend:/app:rw
    command: tail -f /dev/null
