version: '3'

services:
  backend:
    build:
      context: backend
    ports:
      - '6060:6060/tcp'

  envoy:
    build:
      context: envoy
    ports:
      - '3000:3000/tcp'
    depends_on:
      - backend

  frontend:
    build:
      context: frontend
    ports:
      - '80:80/tcp'
    depends_on:
      - envoy
