version: '3'

services:
  backend:
    image: 'golang:1.17'
    working_dir: /go/src/app
    ports:
      - '6060:6060/tcp'
    volumes:
      - ./backend:/go/src/app:rw
    command: tail -f /dev/null

  envoy:
    build:
      context: envoy
    ports:
      - '3000:3000/tcp'
    depends_on:
      - backend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile-dev
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    ports:
      - '80:3000/tcp'
    depends_on:
      - envoy
    volumes:
      - ./frontend:/app:rw
    entrypoint: fixuid
    command: tail -f /dev/null
