FROM golang:1.14-alpine
RUN apk add --no-cache git gcc libc-dev
RUN set -eux \
    && wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.21.0 \
    && golangci-lint --version
RUN addgroup -g 1000 app && \
    adduser -u 1000 -G app -h /home/app -s /bin/sh -D app
RUN set -eux \
    && mkdir /app \
    && chown app:app /app
WORKDIR /app
RUN set -eux \
    && USER=app \
    && GROUP=app \
    && wget -O - -q https://github.com/boxboat/fixuid/releases/download/v0.4/fixuid-0.4-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - \
    && chown root:root /usr/local/bin/fixuid \
    && chmod 4755 /usr/local/bin/fixuid \
    && mkdir -p /etc/fixuid \
    && printf "user: $USER\ngroup: $GROUP\n" > /etc/fixuid/config.yml
